##### AI TECH - Akademia Innowacyjnych Zastosowań Technologii Cyfrowych. Programu Operacyjnego Polska Cyfrowa na lata 2014-2020
<hr>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center>
    <h1 style = "font-size:48px; font-weight:normal"><b>AI</b>-TECH</h1>
    <br>
<br>
<br>
<br>
    <h1 style = "font-size:24px; font-weight:normal">Przykład 5 DO LABORATORIUM 1</h1>
    <h1 style = "font-size:24px">z UCZENIA MASZYNOWEGO</h1>
    <h1 style = "font-size:24px">Regresja liniowa i logistyczna</h1>
    <h1 style = "font-size:24px">Tomasz Neumann</h1>
    <h3 style = "font-size:21px">Regresja logistyczna w StatsModels</h3>
</center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
    </body>
    </html>

![stopka.svg](stopka.svg)

<center>
Projekt współfinansowany ze środków Unii Europejskiej w ramach Europejskiego Funduszu Rozwoju Regionalnego 
Program Operacyjny Polska Cyfrowa na lata 2014-2020,
Oś Priorytetowa nr 3 "Cyfrowe kompetencje społeczeństwa" Działanie  nr 3.2 "Innowacyjne rozwiązania na rzecz aktywizacji cyfrowej" 
Tytuł projektu:  „Akademia Innowacyjnych Zastosowań Technologii Cyfrowych (AI Tech)”
    </center>

<hr>

# 1. Przykład 5

Regresja logistyczna może być także analizowana w Pythonie za pomocą pakietu StatsModels. Procedura postępowania jest podobna jak w <i>scikit-learn</i>, jednak pakiet ten oferuje więcej szczegółowych informacji statystycznych dotyczących modeli i wyników.
Na samym początku należy rozpocząć od zaimportowania biblioteki NumPy oraz <i>statsmodels.api</i>. 

In [2]:
# Import podstawowych bibliotek
import numpy as np
import statsmodels.api as sm

Tak jak poprzednio, na potrzeby tego przykładu stworzymy tablice NumPy równomiernie rozłożonych wartości wejściowych <i>x</i> i wyjściowych <i>y</i>. Należy jednak pamietać, że pakiet StatsModels nie bierze pod uwagę przecięcia (wyrazu wolnego) i należy uwzględnić dodatkową kolumnę 'jedynek' w $x$ (obciążenie), co w prosty sposób można dokonać za pomoca <i>add_constant()</i>.

In [3]:
# Stworzenie przykładowych danych

# Dwuwymiarowa tablica danych wejściowych:
# jedna kolumna dla jednego wejścia, liczba wierszy równa liczbie obserwacji
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])
#dodanie kolumny z jedynkami
x = sm.add_constant(x)

#wyświetlenie kontrolne utworzonych danych
print(x)
print(y)


[[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [1. 8.]
 [1. 9.]]
[0 1 0 0 1 1 1 1 1 1]


Zbudowanie modelu klasyfikacji nastąpi za pomocą klasy <i>statsmodels.discrete.discrete_model.Logit</i>. Należy tutaj pamietać, że pierwszym argumentem są tu wartości zmiennej zależnej y a następnie zmiennej x. (https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.Logit.html).
Trenowanie modelu realizowane jest za pomocą <i>.fit()</i> lub jeżeli ma być wykorzystywana regularyzacja L1, za pomocą metody <i>.fit_regularized()</i>.

In [4]:
# Zbudowanie modelu klasyfikacji za pomocą klasy LogisticRegression
# https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.Logit.html
model = sm.Logit(y, x)
# wytrenowanie modelu na podstawie wcześniej wygenerowanych danych
result = model.fit(method='newton')
#Odkomentuj poniżej trzy linijki, jakby pojawiły się jakieś ostrzeżenia
#import warnings
#from statsmodels.tools.sm_exceptions import ConvergenceWarning
#warnings.simplefilter('ignore', ConvergenceWarning)
result.params

Optimization terminated successfully.
         Current function value: 0.350471
         Iterations 7


array([-1.972805  ,  0.82240094])

Aby sprawdzić wytrenowany model i uzyskać wartość szansy przynależności do danej klasy dla analizowanej obserwacji można użyć metody <i>.predict()</i>.

In [5]:
# Wyświetlenie wyliczonych z modelu prawdopodobieństw
print('Wyznaczone szanse przynależności do danej klasy ("prawdopodobieństwa"):')
print(result.predict(x))
# Przydzielenie do danej klasy z wartością progową 0.5
print("Przynależność do klas:")
print((result.predict(x) >= 0.5).astype(int))

Wyznaczone szanse przynależności do danej klasy ("prawdopodobieństwa"):
[0.12208792 0.24041529 0.41872657 0.62114189 0.78864861 0.89465521
 0.95080891 0.97777369 0.99011108 0.99563083]
Przynależność do klas:
[0 0 0 1 1 1 1 1 1 1]


Wartości, które zostały tu uzyskane można porównać z tymi jakie można uzyskać z wykorzystaniem biblioteki scikit-learn - najprawdopodobniej będą się one różnić od siebie, co jest spowodowane zastosowaniem różnych metod iteracyjnych i procedur oraz innych ustawień parametrów wejściowych.

W celu uzyskania macierzy pomyłek z wytrenowanego modelu można użyć metody <i>.pred_table()</i>, której wartości są typu zmiennoprzecinkowego. 

In [6]:
print(result.pred_table())

[[2. 1.]
 [1. 6.]]


Do uzyskania bardziej szczegółowych statystyk służy metoda <i>sumary()</i>

In [7]:
print(result.summary())

                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                   10
Model:                          Logit   Df Residuals:                        8
Method:                           MLE   Df Model:                            1
Date:                Sat, 26 Mar 2022   Pseudo R-squ.:                  0.4263
Time:                        16:14:50   Log-Likelihood:                -3.5047
converged:                       True   LL-Null:                       -6.1086
Covariance Type:            nonrobust   LLR p-value:                   0.02248
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.9728      1.737     -1.136      0.256      -5.377       1.431
x1             0.8224      0.528      1.557      0.119      -0.213       1.858


bądź metoda <i>sumary2()</i>

In [8]:
print(result.summary2())

                        Results: Logit
Model:              Logit            Pseudo R-squared: 0.426   
Dependent Variable: y                AIC:              11.0094 
Date:               2022-03-26 16:14 BIC:              11.6146 
No. Observations:   10               Log-Likelihood:   -3.5047 
Df Model:           1                LL-Null:          -6.1086 
Df Residuals:       8                LLR p-value:      0.022485
Converged:          1.0000           Scale:            1.0000  
No. Iterations:     7.0000                                     
-----------------------------------------------------------------
          Coef.    Std.Err.      z      P>|z|     [0.025   0.975]
-----------------------------------------------------------------
const    -1.9728     1.7366   -1.1360   0.2560   -5.3765   1.4309
x1        0.8224     0.5281    1.5572   0.1194   -0.2127   1.8575



# Zadania do wykonania

<p><b>Zadanie 1</b></p>
Wczytaj dane z pliku <i>diabetes.csv</i>, wykonaj odpowiednie dopasowanie danych do modelu korzystając z powyższego pakietu oraz przeprowadź przykładową klasyfikację. (W pliku <i>diabetes.csv</i> znajdują się informacje na temat: liczby ciąż, stężenia glukozy w osoczu, ciśnienia rozkurczowego krwi, grubości fałdu mięśnia trójgłowego, insuliny w surowicy krwi, wskaźnika BMI, funkcji powstania cukrzycy na podstawie wywiadu rodzinnego, informację o wieku oraz jako ostatnią wartość informującą czy dana osoba nie ma cukrzycy - '0', czy też ma cukrzycę - '1'. 

In [1]:
# Rozwiązanie Zadania 1
import pandas as pd
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# 1. Wczytanie danych
df = pd.read_csv('diabetes.csv')

# 2. Przygotowanie danych
# X to wszystkie kolumny poza 'Outcome', y to kolumna 'Outcome'
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Dodanie wyrazu wolnego (stałej) niezbędnej dla statsmodels
X = sm.add_constant(X)

# Podział na zbiór treningowy i testowy (np. 80% / 20%) dla rzetelności testu
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Dopasowanie modelu (Regresja logistyczna) na danych treningowych
model_diabetes = sm.Logit(y_train, X_train)
result_diabetes = model_diabetes.fit(method='newton')

print("\n--- Podsumowanie modelu ---")
print(result_diabetes.summary())

# 4. Przykładowa klasyfikacja i ocena na danych testowych
# Zwraca prawdopodobieństwa, więc aplikujemy próg 0.5
y_pred_prob = result_diabetes.predict(X_test)
y_pred = (y_pred_prob >= 0.5).astype(int)

print("\n--- Macierz pomyłek na danych testowych ---")
print(confusion_matrix(y_test, y_pred))

print("\n--- Raport klasyfikacji ---")
print(classification_report(y_test, y_pred))

Optimization terminated successfully.
         Current function value: 0.467835
         Iterations 6

--- Podsumowanie modelu ---
                           Logit Regression Results                           
Dep. Variable:                Outcome   No. Observations:                  614
Model:                          Logit   Df Residuals:                      605
Method:                           MLE   Df Model:                            8
Date:                Mon, 30 Mar 2026   Pseudo R-squ.:                  0.2752
Time:                        16:33:11   Log-Likelihood:                -287.25
converged:                       True   LL-Null:                       -396.34
Covariance Type:            nonrobust   LLR p-value:                 9.311e-43
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -9.0359      0.837    -

![stopka.svg](stopka.svg)

### Wnioski do ćwiczenia 5

Po wczytaniu historycznych danych pacjentów (tzw. zbiór Pima Indians Diabetes) i przetrenowaniu liniowego modelu regresji logistycznej z pakietu `statsmodels` wyciągnęliśmy następujące informacje z przeprowadzonej klasyfikacji:

1. **Statystyki podsumowujące model na podstawie P-value ($P>|z|$):**
   * Pakiet `statsmodels` jest wyjątkowo użyteczny, gdyż z marszu dla każdej cechy zwraca testy statystyczne i wartość `p-value`. Z podsumowania odczytujemy najistotniejsze zmienne ($p < 0.05$). Wpływ na ryzyko i identyfikację cukrzycy najwyraźniej wykazują w tym badaniu: **Glucose** (Poziom glukozy w osoczu) oraz **BMI** (Wskaźnik masy ciała). 
   * Istotne pozostają także **Age** (Wiek), a marginalnie **BloodPressure** i **DiabetesPedigreeFunction**.
   * Cechy uchodzące tu za nieznaczące i potencjalnie słabe statystycznie ($p \geq 0.05$) to np. *SkinThickness* (Grubość fałdu skórnego)

2. **Ocena klasyfikatora:**
   * Algorytm po znalezieniu optymalnych wag iteracyjnie (metoda Newtona) na zbiorze treningowym uzyskał dokładność przewidywania (*Accuracy*) na wydzielonym, niewidzianym wcześniej zbiorze testowym w okolicach **~75%**.
   * Oznacza to, że jest w stanie z całkiem dobrą (acz nie perfekcyjną) skutecznością przewidzieć istnienie choroby. Patrząc po samej macierzy pomyłek i precyzji, możemy dostrzec, że model sprawniej identyfikuje osoby zdrowe (wyższa precyzja i czułość dla klasy `0`), a gorzej radzi sobie z jednoznacznym wskazaniem osób chorych (klasa `1`). Podyktowane jest to lekkim niezbalansowaniem klas w pierwotnym zbiorze (prawie 500 chorych kontra bagatela w pół tysiącu zdrowych kobiet z rdzennego plemienia Pima), co mogliśmy w praktyce zaobserwować wykonując ćwiczenie z zadania pobocznego "4".